### ISSUE TITLE
Config Check fails after Switching RPi 4 to SSD

### ISSUE THREAD

**Issue by 51av0sh** [kevinvincent/ha-wyzesense#214]
A few days ago I migrated my pi setup from SD to SSD. Performed a full restore from my latest snapshot and had a few issues that needed to be fixed relating to the DB but everything else worked fine except the wyzesense integration. I can't get past the config check with the following error:

Platform error binary_sensor.wyzesense - cannot import name 'retry' from 'retry' (/usr/local/lib/python3.8/site-packages/retry/__init__.py)

I setup debug logging for the component but there is absolutely nothing in the logs about wyzesense or any errors

```
logger:
  default: info
  logs:
    custom_components.wyzesense: debug
    wyzesense.gateway: debug
```

I've tried removing the integration, removing HACS, and reinstalling but no dice (several times). I'm lost at this point. Any suggestions?

**Comment by 51av0sh** [comment]
Interesting. Tried rolling back to different versions and it works fine on 0.8. Not ideal since I'd like to be on the latest but I guess that's better than nothing. Would still like to know if I can solve this on the latest version.

**Comment by 51av0sh** [comment]
A little more context. I did a fresh install on a Raspberry Pi 4 B with the 64 bit version of 5.31

**Comment by 51av0sh** [comment]
Well. Looked over the code and noticed this line:

from retry import retry

Since my error was related I decided to manually install retry 0.9.2

https://pypi.org/project/retry/

`pip install retry`

I then installed wyzesense again, installed the bridge, rebooted.. and what do you know? No more errors and the service is now available :)

I hope this might help someone else. Cheers
